GET http://localhost:3003/players/

###
POST http://localhost:3003/players/
Content-Type: application/json
{
    "playerName": "Shiva",
    "jerseyNumber": 03,
    "role": "Bowler"
}
###
GET http://localhost:3003/players/1/
###

PUT http://localhost:3003/players/3/

Content-Type: application/json
{
    "playerName": "Harish",
    "jerseyNumber": 53,
    "role": "Batsman"
}
###
DELETE http://localhost:3003/players/2/